[2023-11-27 20:47:53,196] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:47:53] "[33mGET /usuarios HTTP/1.1[0m" 404 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:04,605] ERROR log_exception() L1741 Exception on /usuario [POST] - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\flask\app.py L1741
Traceback (most recent call last):
  File "C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\flask_openapi3\scaffold.py", line 104, in view_func
    response = func(**result)
  File "C:\_0000_MVP_Final\MVP_ESSI\api\app.py", line 79, in predict
    modelo = Model.carrega_modelo(ml_path)
  File "C:\_0000_MVP_Final\MVP_ESSI\api\model\modelo.py", line 12, in carrega_modelo
    model = pickle.load(open(path, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'ml_model/modelo_ads003.pkl'
[2023-11-27 20:48:04,663] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:48:04] "[35m[1mPOST /usuario HTTP/1.1[0m" 500 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:35,445] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.10:5000 - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:35,446] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:43,164] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:48:43] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:43,174] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:48:43] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:43,937] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:48:43] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:43,939] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:48:43] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:43,942] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:48:43] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:44,881] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:48:44] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:44,900] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:48:44] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:44,908] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:48:44] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:44,913] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:48:44] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:45,175] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:48:45] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:50,306] WARNING get_usuarios() L51   Não há usuários cadastrados na base :/ - call_trace=C:\_0000_MVP_Final\MVP_ESSI\api\app.py L51  
[2023-11-27 20:48:50,307] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:48:50] "[33mGET /usuarios HTTP/1.1[0m" 404 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:48:58,549] ERROR log_exception() L1741 Exception on /usuario [POST] - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\flask\app.py L1741
Traceback (most recent call last):
  File "C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\flask_openapi3\scaffold.py", line 104, in view_func
    response = func(**result)
  File "C:\_0000_MVP_Final\MVP_ESSI\api\app.py", line 79, in predict
    modelo = Model.carrega_modelo(ml_path)
  File "C:\_0000_MVP_Final\MVP_ESSI\api\model\modelo.py", line 12, in carrega_modelo
    model = pickle.load(open(path, 'rb'))
_pickle.UnpicklingError: invalid load key, '\x04'.
[2023-11-27 20:48:58,556] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:48:58] "[35m[1mPOST /usuario HTTP/1.1[0m" 500 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:51:08,535] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.10:5000 - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:51:08,537] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:51:18,030] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:51:18] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:51:18,043] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:51:18] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:51:18,835] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:51:18] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:51:18,837] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:51:18] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:51:18,850] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:51:18] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:51:20,214] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:51:20] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:51:20,233] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:51:20] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:51:20,237] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:51:20] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:51:20,242] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:51:20] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:51:20,477] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:51:20] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
[2023-11-27 20:51:28,247] INFO _log() L224  127.0.0.1 - - [27/Nov/2023 20:51:28] "POST /usuario HTTP/1.1" 200 - - call_trace=C:\Users\Vanessa Paula\Anaconda31\lib\site-packages\werkzeug\_internal.py L224 
